/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

/**
 *
 * @author roberto
 */
public class juego1 extends javax.swing.JFrame {

    /**
     * Creates new form juego1
     */
    public juego1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    int turnos=0;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pb_vida1 = new javax.swing.JProgressBar();
        pb_vida2 = new javax.swing.JProgressBar();
        Bolasombra = new javax.swing.JButton();
        Golpebajo = new javax.swing.JButton();
        Recuperar1 = new javax.swing.JButton();
        Psiquico = new javax.swing.JButton();
        Hiperrayo = new javax.swing.JButton();
        Recuperar2 = new javax.swing.JButton();
        Restaurar = new javax.swing.JButton();
        lb_ganador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/cofagrigus.png"))); // NOI18N
        jLabel1.setText("Jugador1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/mismagius.png"))); // NOI18N
        jLabel2.setText("Jugador2");

        pb_vida1.setBackground(new java.awt.Color(51, 255, 51));
        pb_vida1.setValue(100);

        pb_vida2.setBackground(new java.awt.Color(51, 255, 51));
        pb_vida2.setValue(100);

        Bolasombra.setText("Bola Sombra");
        Bolasombra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BolasombraMousePressed(evt);
            }
        });

        Golpebajo.setText("Golpe Bajo");
        Golpebajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GolpebajoMousePressed(evt);
            }
        });
        Golpebajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolpebajoActionPerformed(evt);
            }
        });

        Recuperar1.setText("Recuperar");
        Recuperar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Recuperar1MousePressed(evt);
            }
        });

        Psiquico.setText("Psiquico");
        Psiquico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PsiquicoMousePressed(evt);
            }
        });

        Hiperrayo.setText("Hiperrayo");
        Hiperrayo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HiperrayoMousePressed(evt);
            }
        });

        Recuperar2.setText("Recuperar");
        Recuperar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Recuperar2MousePressed(evt);
            }
        });

        Restaurar.setText("Restaurar Todo");
        Restaurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RestaurarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pb_vida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lb_ganador))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Recuperar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Golpebajo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bolasombra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pb_vida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Recuperar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(Hiperrayo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Psiquico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(Restaurar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_ganador)
                    .addComponent(pb_vida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pb_vida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bolasombra)
                    .addComponent(Psiquico))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Golpebajo)
                    .addComponent(Hiperrayo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Recuperar1)
                    .addComponent(Recuperar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Restaurar)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GolpebajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolpebajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GolpebajoActionPerformed

    private void BolasombraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BolasombraMousePressed
       if(turnos==0){
            int vida2=pb_vida2.getValue();
            int random = (int)(Math.random()*1000%10);
            vida2-=10+random;
            System.out.println(10+random);
            pb_vida2.setValue(vida2);
            turnos=1;
            if(vida2<=0)
                lb_ganador.setText("Jugador 1 ha ganado");
        }
    }//GEN-LAST:event_BolasombraMousePressed

    private void GolpebajoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GolpebajoMousePressed
         if(turnos==0){
            int vida2=pb_vida1.getValue();
            vida2-=40;
            pb_vida2.setValue(vida2);
            turnos=1;
            if(vida2<=0)
            lb_ganador.setText("Jugador 1 a Ganado");
         }
    }//GEN-LAST:event_GolpebajoMousePressed

    private void Recuperar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Recuperar1MousePressed
         if(turnos==0){
            int vida1=pb_vida1.getValue();
            vida1 +=20;
            pb_vida1.setValue(vida1);
            turnos=1;
        }
    }//GEN-LAST:event_Recuperar1MousePressed

    private void RestaurarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurarMousePressed
         pb_vida1.setValue(100);
        pb_vida2.setValue(100);
        turnos=0;
        lb_ganador.setText(" ");
    }//GEN-LAST:event_RestaurarMousePressed

    private void HiperrayoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HiperrayoMousePressed
                if(turnos==1){
            int vida1=pb_vida1.getValue();
            vida1-=40;
            pb_vida1.setValue(vida1);
            turnos=0;
            if(vida1<=0)
            lb_ganador.setText("Jugador 2 a Ganado");

}
    }//GEN-LAST:event_HiperrayoMousePressed

    private void PsiquicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PsiquicoMousePressed
         if(turnos==1){
            int vida1=pb_vida1.getValue();
            int random =(int)(Math.random()*1000%10);
            vida1-=10+random;
            System.out.println(10+random);
            pb_vida1.setValue(vida1);
            turnos=0;
            if(vida1<=0)
                lb_ganador.setText("Jugador 2 a Ganado");
    }//GEN-LAST:event_PsiquicoMousePressed

    private void Recuperar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Recuperar2MousePressed
        if(turnos==1){
            int vida2=pb_vida2.getValue();
            vida2 +=20;
            pb_vida2.setValue(vida2);
            turnos=0;
        }
    }//GEN-LAST:event_Recuperar2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new juego1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bolasombra;
    private javax.swing.JButton Golpebajo;
    private javax.swing.JButton Hiperrayo;
    private javax.swing.JButton Psiquico;
    private javax.swing.JButton Recuperar1;
    private javax.swing.JButton Recuperar2;
    private javax.swing.JButton Restaurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb_ganador;
    private javax.swing.JProgressBar pb_vida1;
    private javax.swing.JProgressBar pb_vida2;
    // End of variables declaration//GEN-END:variables
}
